# Generated by Django 3.0.4 on 2020-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
