# Generated by Django 3.0.4 on 2020-07-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200721_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text1',
            field=models.TextField(max_length=700),
        ),
    ]
